version: '3'
services: 
    web: 
        build: 
            context: . #specifies where image is going to pull files and folders from
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules #bind this folder inside of the container to be mounted.
            - .:/app #maps folder from outside the container to app folder inside the container
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true